services:
  api:
    environment:
      - MSSQL_SA_PASSWORD=Password1*
    container_name: customerservice
    image: arialind/pizzeria-bravo-customer-service
    # build:
    #   context: .
    #   dockerfile: PizzeriaBravo.CustomerService.API/Dockerfile
    ports:
      - "3002:3002"
    depends_on:
      - docker_sqlserver

  docker_sqlserver:
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password1*
    container_name: docker_sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"