name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository
    - uses: actions/checkout@v4
    
    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    # Build the Docker image with multiple tags
    - name: Build the Docker image with multiple tags
      run: |
        docker build . --file Dockerfile \
          --tag arialind/pizzeriabravo-customerservice-api:latest \
          --tag arialind/pizzeriabravo-customerservice-api:${{ github.run_id }}
          
    # Push the latest Docker image
    - name: Push the latest Docker image
      run: |
        docker push arialind/pizzeriabravo-customerservice-api:latest
        docker push arialind/pizzeriabravo-customerservice-api:${{ github.run_id }}

      
